# Generated by Django 6.0.6 on 2026-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarproducts',
            name='similarity_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
