# Generated by Django 6.0.6 on 2026-08-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysticsSumary',
            new_name='AnalysticsSummary',
        ),
    ]
